# Generated by Django 5.0.3 on 2024-03-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastName', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('FirstName', models.CharField(max_length=50, verbose_name='Имя')),
                ('Patronymic', models.CharField(max_length=50, verbose_name='Отчество')),
                ('BirthDate', models.DateField(verbose_name='Дата рождения')),
                ('RegisterDate', models.DateField(verbose_name='Дата регистрации')),
                ('PhoneNumber', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('Email', models.EmailField(max_length=254, verbose_name='Адрес электронной почты')),
                ('Password', models.CharField(max_length=30, verbose_name='Пароль')),
            ],
        ),
    ]
